# intelligence.toml - Configuração de Blacklist do Motor Nexus

ignore = [
    # === PASTAS ===
    "*./experiments/",
    "*/.doxoade/",
    "*/__pycache__/",
    ".doxoade/",
    ".doxoade_cache/",
    ".git/",
    ".pytest_cache/",
    "__pycache__/",
    "build/",
    "build_soteria_test/",
    "Canone_Test/",
    "commands_test/",
    "dist/",
    "dox_lab/",
    "*.egg-info/",
    "doxoade/diagnostic/",
    "doxoade/tools/benzaiten_gui/native/include/webview/",
    "doxoade/tools/benzaiten_gui/native/include/webview2/",
    "nppBackup/",
    "pytest_temp_dir/",
    "recovery_zone/",
    "regression_tests/",
    "tests/",
    "tmp/",
    "venv/",
    "Vers/",
    "w64devkit/",
    # === EXTENSÕES DE BUILD/SCRIPT ===
    "*.specpython",
    "*.bat",
    "*.sh",
    "*.xml",
    "*.pyd",
    "*.txt",
    "*.json",
    "*.jsonl",
    "*.xml",
    # === EXTENSÕES BINÁRIAS/NATIVAS ===
    "*.hh",
    "*.dll",
    "*.exe",
    # === EXTENSÕES DE BACKUP/LIXO ===
    "*.bkp",
    "*.old",
    "*.bak",
    "*.tmp",
    "*.temp",
    "*.log",
    "*.cache",
    "*.nxa",
    "*.jsonl",
    "*.conf",
    "*.ini",
    "*.whitelist_backup",
    "*.hbc5_backup",
    "*.final_backup",
    # ___ DATABASE _________
    "data/",
    "*.db-journal",
    "*.sqlite",
    "*.sqlite3",
    "*.sqlite-shm",
    "*.sqlite-wal",
    "*.sqlite-journal",
    "*.db",
    "*.db-shm",
    "*.db-wal",
    # ___ RELATÓRIOS _________
    "chief_dossier_*.xml",
    "*_dossier_*.xml",
]
# "*.",
# ""/,